
project:
  type: website

metadata-files:
  - _variables.yml

website:
  title: "POO aplicada ao Comércio Exterior"
  navbar:
    left:
      - href: slides/aula_poo_comex.qmd
        text: Slides

format:
  revealjs:
    theme: simple
    title-slide: false
    footer: "Cafe com Dados"
    slide-number: true
    transition: fade
    code-copy: true
    css: assets/capa.css
execute:
  echo: false
