
project:
  type: website

website:
  title: "POO aplicada ao Comércio Exterior"
  navbar:
    left:
      - href: slides/aula_poo_comex.qmd
        text: Slides

format:
  revealjs:
    theme: simple
    slide-number: true
    transition: fade
    code-copy: true
execute:
  echo: false
