project:
  type: website

metadata-files:
  - _variables.yml

website:
  title: "Bases de Dados de Emprego no Brasil"
  navbar:
    left:
      - href: slides/aula_caged.qmd
        text: CAGED
      - href: slides/aula_rais.qmd
        text: RAIS
      - href: slides/aula_pnad_continua.qmd
        text: PNAD Continua

format:
  revealjs:
    theme: simple
    title-slide: false
    footer: "Cafe com Dados"
    slide-number: true
    transition: fade
    code-copy: true
    css: assets/capa.css

execute:
  echo: false
